services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      JWT_SECRET_KEY: "your-secret-key"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    develop:
        watch:
          - action: sync
            path: ./frontend
            target: /app
            ignore:
              - node_modules

  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data:
