name: Check Commit

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Check Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webiny/action-conventional-commits@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
