name: Checklist CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true
        cache-dependency-path: 'backend/go.sum'
    - name: Verify dependencies
      run: go mod verify
      working-directory: backend
    - name: Build
      run: go build -v ./...
      working-directory: backend
    - name: Format check
      run: |
        if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
          echo "Go code is not formatted correctly:"
          gofmt -d .
          exit 1
        fi
      working-directory: backend
